### ISSUE TITLE
Pretrained models on ImageNet21k vs ImageNet1k

### ISSUE THREAD

**Issue by cbbjames** [Liangqiong/ViT-FL-main#1]
Hi,

Thanks for the interesting work!

May I confirm that are the results of ResNet50 in the paper are pretrained on ImageNet21k as the same as ViT? 
Or is there a ResNet50 ImageNet21k pretrained model that needs to be used here (instead of the ImageNet1k one from official PyTorch)? 
https://github.com/Liangqiong/ViT-FL-main/blob/7521a2ae915747d53cc1de287e852a10002895d4/utils/start_config.py#L73

Thanks!

**Comment by nips-vit-fl-sub** [comment]
The current version here we take the default pretrained models, for ResNet use Image1k, via ViT use Imagenet21k.
We have a new version that also evaluate the VIT with pretrained model on Image1K, but not published yet.

**Comment by Liangqiong** [comment]
The current version here we take the default pretrained models, for ResNet use Image1k, and ViT use Imagenet21k.
We have a new version that also evaluate the VIT with pretrained model on Image1K, but not published yet.

**Comment by cbbjames** [comment]
Thanks!

**Comment by Liangqiong** [comment]
Just an update, the current version, all the pretrained models are from ImageNet1k
