### ISSUE TITLE
About the time cost of vit-Fedavg

### ISSUE THREAD

**Issue by wei0413** [Liangqiong/ViT-FL-main#4]
According to the author's code, under the CIFAR-10 dataset, the time cost of ViT CWT and ViT Fedavg seems to be the same. Is this normal?

**Comment by Liangqiong** [comment]
What time cost do you mean? 
Could you specify more by providing the training loss or something else?

**Comment by wei0413** [comment]
I conducted the experiment on GPU: A40. Among them, under the CIFAR-10 and split 2 data partitions, the time required for ViT -CWT training is 4.7138 hours, and the time required for ViT-Fedavg training is 4.53944 hours. There is no significant difference between them. Even in the split 1 data partition, the time cost of ViT-Fedavg is slightly more than that of ViT-CWT by 0.03 hours. My initial idea is to modify the code of ViT-Fedavg and add the "import thread" thread module. I just started to learn about this, and there may be some misunderstandings~

**Comment by Liangqiong** [comment]
Hi, our code is based on simulation environment. Thus the time cost you calculated is not the actual time cost for FL. 
The communication cost is omitted in my code. Thus the time for for ViT-CWT and ViT-FedAVG is similar in your calculation.

**Comment by wei0413** [comment]
Oh，I See.Thank you~
