### ISSUE TITLE
output_dir is hard coded

### ISSUE THREAD

**Issue by arghavan-kpm** [Liangqiong/ViT-FL-main#6]
In start_config.py > initialization_configure(), at the end when it's trying to update args.output_dir, it hard coded 'output' as the first part of the address. I think it should be changed to args.output_dir itself:
```
args.output_dir = os.path.join(args.output_dir, args.FL_platform, args.dataset, args.name)
```

**Comment by Liangqiong** [comment]
Thanks for this. Modified as suggestion
