### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by Peppepelle99** [Liangqiong/ViT-FL-main#7]
Hi, i don't understand where i have to put the pretrained model that i already downloaded.
In the readme's section 2, i don't know where is located the 'timm' folder.
Furthemore if i run train_FedAVG.py turn out an error in timm (of course) even if i install the timm package.

Thank you in advance. 

Giuseppe Pellegrino.

**Comment by krumpguo** [comment]
> Hi, i don't understand where i have to put the pretrained model that i already downloaded. In the readme's section 2, i don't know where is located the 'timm' folder. Furthemore if i run train_FedAVG.py turn out an error in timm (of course) even if i install the timm package.
> 
> Thank you in advance.
> 
> Giuseppe Pellegrino.

I have the same question.

**Comment by krumpguo** [comment]
> 

![image](https://user-images.githubusercontent.com/117053525/226321575-3bbb86af-4274-445a-ba96-7de005e1fe57.png)
it's here , I have found it !
