### ISSUE TITLE
ViT(T) and ViT(S)

### ISSUE THREAD

**Issue by alessiomora** [Liangqiong/ViT-FL-main#8]
Hi, thank you for your nice paper.

What is the original paper of ViT(T) and ViT(S)? In my opinion, this is unclear both in the code and in your paper. 
Is it from [1]?

Thank you. 

[1] Hugo Touvron, Matthieu Cord, Matthijs Douze, Francisco Massa, Alexandre Sablayrolles, and Hervé Jégou.
Training data-efficient image transformers & distillation through attention. arXiv:2012.12877, 2020.

**Comment by Liangqiong** [comment]
https://github.com/huggingface/pytorch-image-models/blob/main/timm/models/vision_transformer.py
Pretrained model and code is from the above link.
